# This file was originally created by running the command
# rustfmt --dump-default-config rustfmt.toml && sort -u rustfmt.toml -o rustfmt.toml.
# Changes from the defaults are marked with comments.
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
comment_width = 100 # Fuchsia uses 100
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
empty_item_single_line = true
error_on_line_overflow = false # Comments with urls are allways too long
error_on_unformatted = false
fn_args_density = "Compressed" # Fuchsia prefers compressed
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_strings = true # otherwise strings will violate max_width
hard_tabs = false
hide_parse_errors = false
imports_indent = "Visual"
imports_layout = "Mixed"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = false
max_width = 100
merge_derives = true
newline_style = "Unix"
normalize_comments = true # Seems useful
remove_blank_lines_at_start_or_end_of_block = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imported_names = true
reorder_imports = true # This sort of ordering is useful and should be done by a tool
reorder_imports_in_group = true # This sort of ordering is useful and should be done by a tool
reorder_modules = true # This sort of ordering is useful and should be done by a tool
report_fixme = "Never"
report_todo = "Never"
skip_children = false
spaces_around_ranges = false
spaces_within_parens_and_brackets = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = false
use_field_init_shorthand = false
use_small_heuristics = true
use_try_shorthand = true # Fuchsia prefers the shortcut
where_single_line = false
wrap_comments = true # otherwise comments will violate max_width
